### ISSUE TITLE
[ADD] Possibility to go back from Vault import view

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-web#30]
At the moment user does not have possibility to go back to main page when on import page and deciding not to import or if user does not have a import QR.

When clicking "Vultisig" logo at the top going back to main page.

![image](https://github.com/user-attachments/assets/6cf5cc45-ec10-4fe8-8fd2-f57a2abe359c)

**Comment by Ehsan-saradar** [comment]
@realpaaao 
If you click on the back button of your browser if will go back last page 
But if we need to have a button we should update figma (maybe add import/cancel buttons or back icon button)

**Comment by realpaaao** [comment]
@Ehsan-saradar can we not just make the vultisig logo at the top clickable and linking back to web.vultisig.com ? that is super intuative and mobile friendly
